spring:
  datasource:
    url: jdbc:mysql://10.122.157.148:3306/zhangzhi8?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: db_user
    password: 1qazXSW@
    db-name: zhangzhi8
  jpa:
    show-sql: true
    generate-ddl: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  profiles:
    active: lmp-sy-dev

mybatis-plus:
  mapper-locations: classpath*:/com/example/demo/dao/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.demo.model
  global-config:
    id-type: 1  #主键类型 0:数据库ID自增   1:用户输入id  2:全局唯一id(数字类型唯一ID)  3:全局唯一ID(uuid)
    db-column-underline: false  #驼峰下划线转换
    refresh-mapper: true  #刷新mapper 调试神器
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
  #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用